[[ReadStat]]
arch = "aarch64"
git-tree-sha1 = "627207ea759a3499f9b24319a85682855415ca18"
os = "macos"

    [[ReadStat.download]]
    sha256 = "06e96f946208d49e5e1fc95cb30f4e7392ff6f1ba7c22478361e90f47c342800"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.aarch64-apple-darwin.tar.gz"
[[ReadStat]]
arch = "aarch64"
git-tree-sha1 = "32c11e0694b7984d34a82a77ea0fcab969e02be1"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "d5b32deae65b02cf2f6b6cb6514cfb3a5ad628824213a4337fe0a8b97a218824"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.aarch64-linux-gnu.tar.gz"
[[ReadStat]]
arch = "aarch64"
git-tree-sha1 = "ba5833851aa286186b60caa2205e74aed0dd7482"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "0807f836c30b590c0d45ca1afb6e8a012fd8f7ca71bdb4971ef727bced4a4fdf"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.aarch64-linux-musl.tar.gz"
[[ReadStat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "17fd570d9e58621b76330a2eb0c3b6e71bce2cef"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "5f1bfb911b06b3d566fe8df3d39aec4306d689690e4fd038e510a230f255fbde"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.armv6l-linux-gnueabihf.tar.gz"
[[ReadStat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "40928081f712036b087211e7e3af45cac8466562"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "0381f8e0563fb874afb76eeae86faeb48f332177cc6e837a94e799fac12ad63a"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.armv6l-linux-musleabihf.tar.gz"
[[ReadStat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "45c3964ae012bfa20cef68e86f4818e8fd80a6c7"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "ab1be47295ecc269978d8bbf6cd4153a25dc7851be73c4335f2d9e9e5f1681f5"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.armv7l-linux-gnueabihf.tar.gz"
[[ReadStat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "55921c1f3925dad26e9d801ff398ff21f2af71e8"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "09a91bfbd9e686739087f0cd968315bd802a0da9f53d3c4b13c8857f1aead029"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.armv7l-linux-musleabihf.tar.gz"
[[ReadStat]]
arch = "i686"
git-tree-sha1 = "ef7c716a03927d8fb2435d51415d0bf91b24f4ae"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "ddbf960aa9d5200827b7dd1a28a231be61d6e33877feb1ab8d133e5aec0c706f"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.i686-linux-gnu.tar.gz"
[[ReadStat]]
arch = "i686"
git-tree-sha1 = "5c263b88b34cf1181f662fa636c8774bcb42872d"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "3ceea95ea8099b90dbaf51ea4d7daaa120337234b525bf151c5c59ea7ca8d13c"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.i686-linux-musl.tar.gz"
[[ReadStat]]
arch = "i686"
git-tree-sha1 = "630a42f4f7c41f4401eea0b0e3fe8a13f0190b3f"
os = "windows"

    [[ReadStat.download]]
    sha256 = "a48e1d6eacca9abd607b298cce6c98aae88c7d9a4ac371e9bfa2607ea3c60d57"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.i686-w64-mingw32.tar.gz"
[[ReadStat]]
arch = "powerpc64le"
git-tree-sha1 = "033a73daed3ba6d58852ba4a110ed5730438999d"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "49e6457d8e157e9a990b469e7979e45fa18c8ebd69cb05da3f833a0b873b39e5"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.powerpc64le-linux-gnu.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "8b1803ccca82bcf80c0ce70f3f607229063dfc11"
os = "macos"

    [[ReadStat.download]]
    sha256 = "e0cb223b90bfec95f97b2e5989281ed1961d357ecef9f28d0dc91702495572b4"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.x86_64-apple-darwin.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "a1669ae1a09bac5a52bd8fbd3d967c0ff59b5303"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "79fe843b36146d76fce22ba9206ccbd7f5e1f9aca823483ba1c1a1c4953e09d9"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.x86_64-linux-gnu.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "a635ca68263ab952dd0975e3dbf2a2c72f4ba15a"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "0c8382dd808a82f2958c5f565fe3ea2ffd13be414cf7a0f83328d8d4c3eec36e"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.x86_64-linux-musl.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "24939e03339675f525bdf037131f4096730b7a1c"
os = "freebsd"

    [[ReadStat.download]]
    sha256 = "730cb195f9a9e3dc355f69f4e3211841cbc5a5e509c7ff575f45ab87e878aca9"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.x86_64-unknown-freebsd.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "9ddd1f4c45c24811ed51a6230f7fb571226e0c69"
os = "windows"

    [[ReadStat.download]]
    sha256 = "438849fd21257fe213b8dd1734d477ada8a9efb1eb2c54dbc44b98fde0717234"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.9+0/ReadStat.v1.1.9.x86_64-w64-mingw32.tar.gz"
