[[ReadStat]]
arch = "aarch64"
git-tree-sha1 = "d883538e574bf4604d1bead59a46740d625cff2b"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "12cc8d81d6f55171d5f30476492a2b7a29f292917530359165e04b950694bcd0"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.aarch64-linux-gnu.tar.gz"
[[ReadStat]]
arch = "aarch64"
git-tree-sha1 = "2f2ee59de2ed9d41d39637f7b16ec8adbdc5f4b7"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "0b2b7ebaf87376077fb4ed9aae722bc893bd502b7a81b7856d6ec44f59a60f8e"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.aarch64-linux-musl.tar.gz"
[[ReadStat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6a16cfcc5c5511792a44569a9bbf7ab02b9816c7"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "685ce5f2d58bb085de53f3d9c14958592ea396e617d946cddfecf7270d4d18d4"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.armv7l-linux-gnueabihf.tar.gz"
[[ReadStat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d2dbdfcafa34cd8aa39599e3552e795d28a7844"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "86b826a4d19f8025e952993e0f0d5b41b759ec138d1f5b3d3a42136734c27b3e"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.armv7l-linux-musleabihf.tar.gz"
[[ReadStat]]
arch = "i686"
git-tree-sha1 = "22757df7543352746a78f8df58b59807565691a6"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "99cde403f4f1fa40b270697b4c3ed4ae9c552ad4042c84616a85fa81e8194421"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.i686-linux-gnu.tar.gz"
[[ReadStat]]
arch = "i686"
git-tree-sha1 = "d43327e664a51b45658e0a09cd1ef8cf0b1a28b6"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "a8326ae4fad89053574fdc482f619f3294148d407b95b6288e4eda4c179a5464"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.i686-linux-musl.tar.gz"
[[ReadStat]]
arch = "i686"
git-tree-sha1 = "351fdfbff33a3f8bfef1ecce07693fc1b7ce623b"
os = "windows"

    [[ReadStat.download]]
    sha256 = "f1e60030fd51c81b226b2c0fbeb96e72c6a65d92fa80870dcb5baa77b9da01bc"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.i686-w64-mingw32.tar.gz"
[[ReadStat]]
arch = "powerpc64le"
git-tree-sha1 = "08201f8c41b7adb1ba1980e9b15b4530b8583da8"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "f483a03ae441026f374de5bc5976b7c1acdd2588e95688badc26cf783c3d800a"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.powerpc64le-linux-gnu.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "3ce9ef1388b28493718c61a56d4c8815bacd4edd"
os = "macos"

    [[ReadStat.download]]
    sha256 = "96abca73c0ad6e115d76c7aa474ad9e6d5d314b5eafa455775f8db001f513665"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.x86_64-apple-darwin.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "a2c39a0a2d1d7802151d4e135c738717f4f5b2e6"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "daff6b94ddd6e35a4a552c9e84b0239b131da98d0c53485acfa0fd2a4335d87f"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.x86_64-linux-gnu.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "73a84952a01aa6d7bfc5ef9258428481bd942eb0"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "05acf78da9127b161741563c249b30d9be4a681d4f0857b0fe528076b1d33f0d"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.x86_64-linux-musl.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "08bfbdb1188e871dd82062e00140bf302401f2fe"
os = "freebsd"

    [[ReadStat.download]]
    sha256 = "98f489d81cd96746cb88563cd357c95d06375144950a96b050f757d5bdfd4dbe"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.x86_64-unknown-freebsd.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "d840297724abe6caa44762930ce2e0cbde6f106b"
os = "windows"

    [[ReadStat.download]]
    sha256 = "6cbcf10ba3667db6ee7776009448c65ed9c639e57164bee8479e898abd403590"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.5+0/ReadStat.v1.1.5.x86_64-w64-mingw32.tar.gz"
