[[ReadStat]]
arch = "armv7l"
git-tree-sha1 = "55f65607d64f0603efd9b66a7a0c3037946dfe13"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "b9335d17c4ee37b9d99fe9184d35ab73a6aa3837e8c701c853c0c4698bf98e6e"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.arm-linux-gnueabihf.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "3a98db37aa30519af050aaabe836f6d1d8ab1646"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "bfa94dae229964fcc498d6c2d47ae68289c5621a9764595b1a9ddb463a302780"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.x86_64-linux-gnu.tar.gz"
[[ReadStat]]
arch = "aarch64"
git-tree-sha1 = "b4a238828a49016faed959978e7317ac30e37d3f"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "f579fc8692c976cc0b3007337c29b44800bf43e944cb96f6ed1d4594b5b6b1d9"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.aarch64-linux-musl.tar.gz"
[[ReadStat]]
arch = "powerpc64le"
git-tree-sha1 = "b6c710de9e9a92636fd4fa45be077c5933be2eb8"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "3a2fe4f8b833b696fb6713b23b371a8f04dff296f29612bfb9f828caabd17b2c"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.powerpc64le-linux-gnu.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "b72f62d9e70bbb365f167bcb7e4ca193a2583ab4"
os = "macos"

    [[ReadStat.download]]
    sha256 = "fc9c0d80dfab86c55c4f57eb04e3be7b8573d3e2b36cb43907a76333175cab5d"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.x86_64-apple-darwin14.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "4ee0827bc454c117267bc56f0a26e1024cadc4c4"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "586ed3e5498ae89fbd5c3ee4f42093de8f43153f2605b4f8716dbb48c1074026"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.x86_64-linux-musl.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "41bceeca455448abee862185789ffc7f303236ff"
os = "windows"

    [[ReadStat.download]]
    sha256 = "6ed7e107504d20cbf72e2ccc8ecce22f974ba676771c475f14211705741a2086"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.x86_64-w64-mingw32.tar.gz"
[[ReadStat]]
arch = "i686"
git-tree-sha1 = "bdc88c825a93e6d589a92901ec6f46225df3cc9c"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "a690c56f88e36168fb2da89e416539385ed75ae2b2a0889087d0a2e717d29956"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.i686-linux-gnu.tar.gz"
[[ReadStat]]
arch = "aarch64"
git-tree-sha1 = "ab86aaca868112f84d23c2e5d837efb0396cf283"
libc = "glibc"
os = "linux"

    [[ReadStat.download]]
    sha256 = "38900f27a832a1be46ac57f52d4d468bf593a052e34ee8b43284b525a8015131"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.aarch64-linux-gnu.tar.gz"
[[ReadStat]]
arch = "i686"
git-tree-sha1 = "1cb60d3d327cba92eee5a72f59eb79de854ae2b0"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "bdc9fac95346a2f34e78759891bc5cb6eff69277c0c11ed4e7d25f20bd4c10cb"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.i686-linux-musl.tar.gz"
[[ReadStat]]
arch = "x86_64"
git-tree-sha1 = "f26bbdf6bfe74b023a5443def734bb9531d6d137"
os = "freebsd"

    [[ReadStat.download]]
    sha256 = "739825d7efcbeed09e4f7aec4a0f62a9a3389368f836a43801f728e85e2db626"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.x86_64-unknown-freebsd11.1.tar.gz"
[[ReadStat]]
arch = "i686"
git-tree-sha1 = "0d92ee3015141725d044d8192c00ba9532bcc482"
os = "windows"

    [[ReadStat.download]]
    sha256 = "3aeb2aa8b5471d08cacd1cc05cbfc758a095e468940e8e7172c172ac9cd13930"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.i686-w64-mingw32.tar.gz"
[[ReadStat]]
arch = "armv7l"
git-tree-sha1 = "4dba9d6eab20148f3cc7576179bb5eb9ec3c52f5"
libc = "musl"
os = "linux"

    [[ReadStat.download]]
    sha256 = "2db680706a7d89a23bcd462cdfbb3c4be66bf9b04229dcea2b7e664e18312245"
    url = "https://github.com/JuliaBinaryWrappers/ReadStat_jll.jl/releases/download/ReadStat-v1.1.1+0/ReadStat.v1.1.1.arm-linux-musleabihf.tar.gz"
